name: Update README

on:
  schedule:
    # Runs at 12 AM daily
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Calculate Lines of Code
      id: loc
      run: |
        loc=$(git ls-files | xargs wc -l | grep total | awk '{print $1}')
        echo "LOC=$loc" >> $GITHUB_ENV

    - name: Fetch GitHub Stats
      id: github_stats
      run: |
        total_contributions=$(curl -s https://api.github.com/users/himasnhu-at | jq .public_repos)
        public_repos=$(curl -s https://api.github.com/users/himasnhu-at | jq .public_repos)
        private_repos=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user/repos?per_page=1 | jq '. | length')
        lifetime_contributions=$(curl -s https://github-contributions-api.now.sh/v1/himasnhu-at | jq '.years[0].total')

        echo "TOTAL_CONTRIBUTIONS=$total_contributions" >> $GITHUB_ENV
        echo "PUBLIC_REPOS=$public_repos" >> $GITHUB_ENV
        echo "PRIVATE_REPOS=$private_repos" >> $GITHUB_ENV
        echo "LIFETIME_CONTRIBUTIONS=$lifetime_contributions" >> $GITHUB_ENV

    - name: Update README.md
      run: |
        LOC=$(echo ${{ env.LOC }})
        TOTAL_CONTRIBUTIONS=$(echo ${{ env.TOTAL_CONTRIBUTIONS }})
        PUBLIC_REPOS=$(echo ${{ env.PUBLIC_REPOS }})
        PRIVATE_REPOS=$(echo ${{ env.PRIVATE_REPOS }})
        LIFETIME_CONTRIBUTIONS=$(echo ${{ env.LIFETIME_CONTRIBUTIONS }})

        sed -i "s|![Lines of Code](.*)|![Lines of Code](https://img.shields.io/badge/LOC-${LOC}%20Lines-blue)|" README.md
        sed -i "/---/,+5d" README.md
        echo -e "---\n** My Github Stats **\n\n> $TOTAL_CONTRIBUTIONS contributions in 2024\n  >\n> $LIFETIME_CONTRIBUTIONS lifetime contributions\n  >\n> $PRIVATE_REPOS private repositories\n  >\n> $PUBLIC_REPOS public repositories\n---" >> README.md

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update README with latest stats"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
